[workspace]
members = ["crates/nickel-session", "crates/nickel-ui"]
default-members = ["crates/nickel-ui"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.94"

[workspace.dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
bitflags = "2.11.0"
freedesktop-desktop-entry = { version = "0.8.1", default-features = false }
freedesktop-icons = "0.4.0"
glyphon = "0.12.0"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
jiff = "0.2.34"
nucleo-matcher = "0.3.1"
pollster = "0.4.0"
redb = "4.1.0"
resvg = "0.47.0"
smithay = { version = "0.7.0", default-features = false, features = ["backend_winit", "wayland_frontend", "desktop"] }
shlex = "1.3.0"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
wgpu = "30.0.0"
winit = "0.30.12"
