[package]
name = "nickel-settings"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nickel-ui = { path = "../nickel-ui" }
nickel-core = { path = "../nickel-core" }
nickel-i18n = { path = "../nickel-i18n" }
nickel-logging = { path = "../nickel-logging" }
nickel-platform = { path = "../nickel-platform" }
image.workspace = true
resvg.workspace = true
tracing.workspace = true
sdl3.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zbus.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_WiFi",
    "Win32_Networking_WinSock",
] }

[target.'cfg(target_os = "windows")'.build-dependencies]
ico.workspace = true
image.workspace = true
winresource.workspace = true
