[package]
name = "twinkle"
version = "0.2.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Declarative native Rust UI with intrinsic layout and native presentation"
readme = "README.md"

[dependencies]
cosmic-text.workspace = true
gilrs.workspace = true
image.workspace = true
twinkle-input = { path = "../twinkle-input", features = ["gilrs", "winit"] }
twinkle-render-assets = { path = "../twinkle-render-assets" }
twinkle-macros = { path = "../twinkle-macros" }
softbuffer.workspace = true
winit.workspace = true
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control", "image-data"] }
smallvec.workspace = true
unicode-segmentation.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_System_Com", "Win32_System_Ole", "Win32_System_SystemServices", "Win32_UI_Shell", "Win32_UI_Shell_Common"] }
windows-core = "0.62.2"

[dev-dependencies]
proptest.workspace = true
sha2.workspace = true
toml.workspace = true
