[package]
name = "nickel-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
nickel-input = { path = "../nickel-input", features = ["windows"] }
nickel-storage = { path = "../nickel-storage" }

[dev-dependencies]
tempfile = "3.25.0"

[target.'cfg(unix)'.dev-dependencies]
libc.workspace = true
