[package]
name = "nickel-ui"
version = "0.1.0"
default-run = "nickel-ui"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck.workspace = true
glyphon.workspace = true
image.workspace = true
jiff.workspace = true
nickel-core = { path = "../nickel-core" }
nucleo-matcher.workspace = true
pollster.workspace = true
redb.workspace = true
resvg.workspace = true
wgpu.workspace = true
winit.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop-desktop-entry.workspace = true
freedesktop-icons.workspace = true
shlex.workspace = true
zbus.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
    "Win32_System_DataExchange",
    "Win32_System_Com",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tempfile = "3.25.0"
